"""add analytics snapshots

Revision ID: 646963aeb0d4
Revises: 650fba13e574
Create Date: 2026-08-16 20:49:28.870482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '646963aeb0d4'
down_revision: Union[str, Sequence[str], None] = '650fba13e574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucket', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('dimensions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analytics_snapshots_bucket', 'analytics_snapshots', ['bucket'], unique=False)
    op.create_index('ix_analytics_snapshots_created_at', 'analytics_snapshots', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analytics_snapshots_created_at', table_name='analytics_snapshots')
    op.drop_index('ix_analytics_snapshots_bucket', table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    # ### end Alembic commands ###
