"""add occurred_at to acquisition_events

Revision ID: 650fba13e574
Revises: 665dcea92452
Create Date: 2026-08-16 20:43:46.268578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '650fba13e574'
down_revision: Union[str, Sequence[str], None] = '665dcea92452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acquisition_events', sa.Column('occurred_at', sa.DateTime(), nullable=True))
    op.create_index('ix_acquisition_events_occurred_at', 'acquisition_events', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_acquisition_events_occurred_at', table_name='acquisition_events')
    op.drop_column('acquisition_events', 'occurred_at')
    # ### end Alembic commands ###
