"""add arr quality profiles root folders and item tables

Revision ID: 665dcea92452
Revises: 0e253b637116
Create Date: 2026-08-16 20:43:03.586174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '665dcea92452'
down_revision: Union[str, Sequence[str], None] = '0e253b637116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arr_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quality_profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('root_folder_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['arr_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_arr_movies_source_id_external_id', 'arr_movies', ['source_id', 'external_id'], unique=True)
    op.create_table('arr_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quality_profile_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('root_folder_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tvdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['arr_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_arr_series_source_id_external_id', 'arr_series', ['source_id', 'external_id'], unique=True)
    op.create_table('quality_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cutoff_format_score', sa.Integer(), nullable=True),
    sa.Column('min_format_score', sa.Integer(), nullable=True),
    sa.Column('items', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['arr_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quality_profiles_source_id_name', 'quality_profiles', ['source_id', 'name'], unique=True)
    op.create_table('root_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('free_space', sa.Integer(), nullable=True),
    sa.Column('unmapped_folders', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['arr_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_root_folders_source_id_path', 'root_folders', ['source_id', 'path'], unique=True)
    op.create_table('arr_episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['arr_series.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['arr_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_arr_episodes_series_id_external_id', 'arr_episodes', ['series_id', 'external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_arr_episodes_series_id_external_id', table_name='arr_episodes')
    op.drop_table('arr_episodes')
    op.drop_index('ix_root_folders_source_id_path', table_name='root_folders')
    op.drop_table('root_folders')
    op.drop_index('ix_quality_profiles_source_id_name', table_name='quality_profiles')
    op.drop_table('quality_profiles')
    op.drop_index('ix_arr_series_source_id_external_id', table_name='arr_series')
    op.drop_table('arr_series')
    op.drop_index('ix_arr_movies_source_id_external_id', table_name='arr_movies')
    op.drop_table('arr_movies')
    # ### end Alembic commands ###
