"""add download_id and download_progress to acquisition_items

Revision ID: 94e6c8aaec58
Revises: 5921e715a15b
Create Date: 2026-08-30 16:06:43.334425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e6c8aaec58'
down_revision: Union[str, Sequence[str], None] = '5921e715a15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acquisition_items', sa.Column('download_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('acquisition_items', sa.Column('download_progress', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_acquisition_items_download_id'), 'acquisition_items', ['download_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acquisition_items_download_id'), table_name='acquisition_items')
    op.drop_column('acquisition_items', 'download_progress')
    op.drop_column('acquisition_items', 'download_id')
    # ### end Alembic commands ###
