"""add correlation note to log events

Revision ID: b993976a2674
Revises: 646963aeb0d4
Create Date: 2026-08-16 20:52:27.263743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b993976a2674'
down_revision: Union[str, Sequence[str], None] = '646963aeb0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_events_raw', sa.Column('correlation_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_events_raw', 'correlation_note')
    # ### end Alembic commands ###
